### ISSUE TITLE
installer role does not re-run the installer when needed

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-operations-collection#12]
##### SUMMARY

The `installer` role currently checks `foreman-installer --noop` on existing installs, and only runs the real deal when that exited `2`.

This is due to three things:
1. we don't call the installer with `--detailed-exitcodes`, which means that in the case Puppet exited with [0,2], Installer will exit with 0 (https://github.com/theforeman/foreman-installer/blob/8610c990613c53c9f81b5f7f5e57918eb5e8588a/bin/foreman-installer#L11)
2. we don't pass `installer_options` to the `--noop` call, so if all that changed was the user adding an option, this won't be detected.
3. Puppet does not exit 2 when run with `--noop` (https://tickets.puppetlabs.com/browse/PUP-686)

1 and 2 are solved in #11 
3 needs a different fix, probably dropping the `--noop` logic for now, and bring it back when Kafo can gather "things would have changed" from Puppet reports

##### STEPS TO REPRODUCE

```yaml
roles:
- role: theforeman.operations.installer
  vars:
    installer_scenario: foreman
- role: theforeman.operations.installer
  vars:
    installer_scenario: foreman
    installer_options:
      - '--enable-foreman-plugin-ansible'
```

##### EXPECTED RESULTS
Ansible plugin enabled

##### ACTUAL RESULTS
Second invocation didn't trigger a real installer run
