### ISSUE TITLE
when using the installer role the 'foreman installer options' cannot have whitespace in the values

### ISSUE THREAD

**Issue by RobVerduijn** [theforeman/foreman-operations-collection#44]
##### SUMMARY

when using the installer role the 'foreman installer options' cannot have whitespace in the values

the following option will cause the installer role to fail:
 --foreman-initial-organization 'My Personal Test Corp'

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.11.4] 
  config file = /home/rob/code/playbooks/ansible.cfg
  configured module search path = ['/home/rob/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rob/code/playbooks/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/rob/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rob/code/playbooks/venv/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/rob/.ansible/collections/ansible_collections
Collection                Version
------------------------- -------
ansible.netcommon         2.4.0  
ansible.posix             1.3.0  
ansible.utils             2.3.1  
community.crypto          1.7.1  
community.general         3.6.0  
fedora.linux_system_roles 1.8.4  
theforeman.foreman        2.2.0  
theforeman.operations     0.3.0
```

##### KATELLO/FOREMAN VERSION

```
package tfm-rubygem-katello is not installed
foreman-3.0.0-0.1.rc2.el8.noarch
```

##### STEPS TO REPRODUCE

```yaml
    - name: run  the foreman-installer
      include_role:
        name: theforeman.operations.installer
      vars:
        foreman_installer_options:
          - '--foreman-initial-organization \"My Personal Test Corp\"'
          - '--foreman-initial-location homeoffice'
```

##### ACTUAL RESULTS

script fails claiming there are to many arguments

```

```
