### ISSUE TITLE
foreman-installer-katello is not installed when foreman_installer_scenario is set

### ISSUE THREAD

**Issue by alvinstarr** [theforeman/foreman-operations-collection#91]
##### SUMMARY
Creating a new foreman with katello install using the Operations collection fails because katello is not installed.
Although the approprate variables are set and the katello repo is installed.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```ansible 2.9.27
  config file = /home/alvin/Customers/StorageGuardian/ansible/SONiC/ansible.cfg
  configured module search path = ['/home/alvin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.12 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
```

##### COLLECTION VERSION

```
[alvin@alvin SONiC]$ ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
[alvin@alvin SONiC]$ ansible-galaxy  --version
ansible-galaxy 2.9.27
  config file = /home/alvin/Customers/StorageGuardian/ansible/SONiC/ansible.cfg
  configured module search path = ['/home/alvin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.9.12 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
```

##### KATELLO/FOREMAN VERSION

`[root@foreman-test ~]# rpm -q tfm-rubygem-katello foreman
package tfm-rubygem-katello is not installed
foreman-3.2.0-1.el8.noarch
``

```

##### STEPS TO REPRODUCE
<!-- For bugs, show exactly how to reproduce the problem, using a minimal test-case. -->

<!-- Paste example playbook below -->
```yaml
---
- hosts:
  - foreman-test
  strategy: free
  become: yes
  gather_facts: true
  remote_user: root
  collections:
    - theforeman.operations
    - theforeman.foreman



  vars:
    foreman_user: "alvin"
    foreman_pass: "fart4u2"
    foreman_repositories_version: "3.2"
    foreman_repositories_katello_version: "4.4"
    foreman_installer_scenario: katello
    foreman_installer_options:
      - '--foreman-initial-admin-email "alvin@netvel.net"'
      - '--foreman-initial-admin-first-name "Alvin"'
      - '--foreman-initial-admin-last-name "Starr"'
      - '--foreman-initial-admin-password "mypassword"'
      - '--foreman-initial-admin-username "alvin"'
      - '--foreman-initial-location "Markham"'
      - '--foreman-initial-organization "Netvel"'
      - '--foreman-cli-password "mypassword"'
      - '--foreman-cli-username "alvin"'


  roles:
    - role: puppet_repositories
    - role: foreman_repositories
#    - role: postgresql_upgrade
    - role: theforeman.operations.installer

```

##### EXPECTED RESULTS

the playbook should not fail.

I found a work around by editing .../operations/roles/installer/tasks/main.yml
and adding 
```- name: "Install Katello"
  package:
    name: "katello"
    state: present
  when:
    - foreman_repositories_katello_version is defined
```
after the foreman_installer_package is installed.
It is likely not the most optimal solution but does seem to work.

##### ACTUAL RESULTS

```
fatal: [foreman-test]: FAILED! => {"ansible_job_id": "191367996189.7451", "attempts": 1, "changed": false, "cmd": ["foreman-installer", "--scenario", "katello", "-v", "--foreman-initial-organization",
[snip]
 "--detailed-exitcodes"], "delta": "0:00:00.522952", "end": "2022-05-19 09:16:21.844428", "failed_when_result": true, "finished": 1, "msg": "non-zero return code", "rc": 26, "start": "2022-05-19 09:16:21.321476", "stderr": "ERROR: Scenario (/etc/foreman-installer/scenarios.d/katello.yaml) was not found, can not continue", "stderr_lines": ["ERROR: Scenario (/etc/foreman-installer/scenarios.d/katello.yaml) was not found, can not continue"], "stdout": "", "stdout_lines": []}

```
